/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontSize: {
      xxs: '0.4rem',
      xs: '0.6rem',
      sm: '14px',
      base: '1.1rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.953rem',
      '4xl': '2.441rem',
      '5xl': '3.052rem',
    },
    colors: {
      transparent: 'transparent',
      'base-900': '#123661',
      white: '#ffffff',
      'base-light': '#f1f7fe',
      'base-600': '#0e4e96',
      'base-500': '#1e7ed9',
      'gray-100': '#f6f6f6;',
      // 'purple': '#3f3cbb',
      // 'midnight': '#121063',
      // 'metal': '#565584',
      // 'tahiti': '#3ab7bf',
      // 'silver': '#ecebff',
      // 'bubble-gum': '#ff77e9',
      // 'bermuda': '#78dcca',
    },
    extend: {},
  },
  plugins: [],
};
